default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost 

development:
  <<: *default
  database: games_app_development

test:
  <<: *default
  database: games_app_test

production:
  <<: *default
  database: games_app_production
  username: postgres
  password: 1234
